[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "m3vae"
version = "0.1.1"
authors = [
  { name="TianMiaoMiao", email="Tmm18846175562@163.com" }
]
description = "M3VAE: Multi‑Modal Metabolic Variational Auto‑Encoder for spatial transcriptomics"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE*"]
requires-python = ">=3.10"
keywords = ["spatial‑transcriptomics", "metabolism", "variational‑autoencoder", "bioinformatics"]


classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=1.23",
    "torch>=2.0",
    "pandas>=1.5",
    "scanpy>=1.9",
    "matplotlib>=3.6",
    "scikit-learn>=1.2",
    "tqdm"
]

[project.scripts]
m3vae = "m3vae.M3VAE:cli_main"

[project.urls]
"Homepage" = "https://github.com/TianMiaoMiaoWorkspace/M3VAE"
"Bug Tracker" = "https://github.com/TianMiaoMiaoWorkspace/M3VAE/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["m3vae*"]

[tool.setuptools.package-data]
"m3vae" = ["data/*"]
